spurious_bg_template = [
 lambda c: f'a photo of a {c} surrounded by fall and autumn leaves.',
 lambda c: f'a photo of a {c} surrounded by flowers.',
 lambda c: f'a photo of a {c} in urban settings.',
 lambda c: f'a photo of a {c} surrounded by greenery.',
 lambda c: f'a photo of a {c} in snowy landscapes.',
 lambda c: f'a photo of a {c} during sunrise.',
 lambda c: f'a photo of a {c} in a rainforest.',
 lambda c: f'a photo of a {c} on busy roads and highways.',
 lambda c: f'a photo of a {c} in the mountains.',
 lambda c: f'a photo of a {c} in tropical landscapes.',
 lambda c: f'a photo of a {c} in winter landscapes.',
 lambda c: f'a photo of a {c} in parks and gardens.',
 lambda c: f'a photo of a {c} in front of historical landmarks.',
 lambda c: f'a photo of a {c} in fields.',
 lambda c: f'a photo of a {c} surrounded by birds.',
 lambda c: f'a photo of a {c} surrounded by fish.',
 lambda c: f'a photo of a {c} in religious centers.',
 lambda c: f'a photo of a {c} surrounded by spring and blooming flowers.',
 lambda c: f'a photo of a {c} near water bodies.',
 lambda c: f'a photo of a {c} in the forest and woods.',
 lambda c: f'a photo of a {c} in a field of grass.',
 lambda c: f'a photo of a {c} surrounded by nature.',
 lambda c: f'a photo of a {c} among rocks.',
 lambda c: f'a photo of a {c} in the snow.',
 lambda c: f'a photo of a {c} in an urban setting.',
 lambda c: f'a photo of a {c} in low crime areas.',
 lambda c: f'a photo of a {c} in rainy weather.',
 lambda c: f'a photo of a {c} on the beach.',
 lambda c: f'a photo of a {c} in the mountains and hills.',
 lambda c: f'a photo of a {c} on the beaches.',
 lambda c: f'a photo of a {c} with the sky as the backdrop.',
 lambda c: f'a photo of a {c} near water.',
 lambda c: f'a photo of a {c} in a popular tourist destination.',
 lambda c: f'a photo of a {c} with insects in the background.',
 lambda c: f'a photo of a {c} in a farmland.',
 lambda c: f'a photo of a {c} in cultural centers.',
 lambda c: f'a photo of a {c} on the sand and beach.',
 lambda c: f'a photo of a {c} with animals in the frame.',
 lambda c: f'a photo of a {c} in entertainment centers.',
 lambda c: f'a photo of a {c} in a suburban area.',
 lambda c: f'a photo of a {c} under a blue sky.',
 lambda c: f'a photo of a {c} surrounded by butterflies.',
 lambda c: f'a photo of a {c} with clouds in the background.',
 lambda c: f'a photo of a {c} in cloudy weather.',
 lambda c: f'a photo of a {c} in commercial areas.',
 lambda c: f'a photo of a {c} in the desert.',
 lambda c: f'a photo of a {c} with desert landscapes in the background.',
 lambda c: f'a photo of a {c} in a forest.',
 lambda c: f'a photo of a {c} in high crime areas.',
 lambda c: f'a photo of a {c} in an industrial setting.',
 lambda c: f'a photo of a {c} in residential areas.',
 lambda c: f'a photo of a {c} in rural areas.',
 lambda c: f'a photo of a {c} in rural settings.',
 lambda c: f'a photo of a {c} in sports stadiums and arenas.',
 lambda c: f'a photo of a {c} during sunset.',
 lambda c: f'a photo of a {c} during sunsets.',
 lambda c: f'a photo of a {c} surrounded by trees.',
 lambda c: f'a photo of a {c} in village and countryside areas.'
]